version: '3.8'

services:
  amp-manager:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./workspace:/workspace
      - amp-config:/home/appuser/.config
    environment:
      - AMP_LOG_LEVEL=debug
      - TMUX_SESSION=amp-manager
    working_dir: /workspace
    tty: true
    stdin_open: true
    command: ["--session", "amp-manager", "--port", "8080"]

volumes:
  amp-config:
